/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviemanagementsystem;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaarlosasiang
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Movie Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JDesktopPane();
        manageMoviesBtn = new javax.swing.JButton();
        manageActor = new javax.swing.JButton();
        manageDirector = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(5, 32, 34));

        mainFrame.setBackground(new java.awt.Color(73, 80, 87));

        manageMoviesBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageMoviesBtn.setText("Manage Movies");
        manageMoviesBtn.setAlignmentX(0.5F);
        manageMoviesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageMoviesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMoviesBtnActionPerformed(evt);
            }
        });

        manageActor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageActor.setText("Manage Actors");
        manageActor.setAlignmentX(0.5F);
        manageActor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageActorActionPerformed(evt);
            }
        });

        manageDirector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageDirector.setText("Manage Directors");
        manageDirector.setAlignmentX(0.5F);
        manageDirector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageDirector.setHideActionText(true);
        manageDirector.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageDirector.setInheritsPopupMenu(true);
        manageDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDirectorActionPerformed(evt);
            }
        });

        mainFrame.setLayer(manageMoviesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainFrame.setLayer(manageActor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainFrame.setLayer(manageDirector, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(manageMoviesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageActor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(306, 306, 306))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(manageActor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageMoviesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(261, 261, 261))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageMoviesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMoviesBtnActionPerformed
        // TODO add your handling code here:
        MovieGui movie = new MovieGui();
        this.mainFrame.add(movie);
        movie.setVisible(true);
    }//GEN-LAST:event_manageMoviesBtnActionPerformed

    private void manageActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageActorActionPerformed
       ActorGui actor = new ActorGui();
       this.mainFrame.add(actor);
       actor.setVisible(true);
    }//GEN-LAST:event_manageActorActionPerformed

    private void manageDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDirectorActionPerformed
        DirectorGui director = new DirectorGui();
       this.mainFrame.add(director);
       director.setVisible(true);
    }//GEN-LAST:event_manageDirectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane mainFrame;
    private javax.swing.JButton manageActor;
    private javax.swing.JButton manageDirector;
    private javax.swing.JButton manageMoviesBtn;
    // End of variables declaration//GEN-END:variables
}
